# Generated by Django 2.0.2 on 2018-04-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bad_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='question',
            name='link',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
