# Generated by Django 2.0.2 on 2018-04-03 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180403_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(default='image/default.jpg', upload_to='image'),
        ),
    ]
