# Generated by Django 2.0.2 on 2018-04-03 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180403_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
