# Generated by Django 2.0.2 on 2018-04-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.IntegerField(default=1),
        ),
    ]
